const CASE = {
  fields: [
    { label: "Case ID", name: "Id", type: "id", picklistValues: [] },
    {
      label: "Deleted",
      name: "IsDeleted",
      type: "boolean",
      picklistValues: [],
    },
    {
      label: "Master Record ID",
      name: "MasterRecordId",
      type: "reference",
      picklistValues: [],
    },
    {
      label: "Case Number",
      name: "CaseNumber",
      type: "string",
      picklistValues: [],
    },
    {
      label: "Contact ID",
      name: "ContactId",
      type: "reference",
      picklistValues: [],
    },
    {
      label: "Account ID",
      name: "AccountId",
      type: "reference",
      picklistValues: [],
    },
    {
      label: "Asset ID",
      name: "AssetId",
      type: "reference",
      picklistValues: [],
    },
    {
      label: "Parent Case ID",
      name: "ParentId",
      type: "reference",
      picklistValues: [],
    },
    { label: "Name", name: "SuppliedName", type: "string", picklistValues: [] },
    {
      label: "Email Address",
      name: "SuppliedEmail",
      type: "email",
      picklistValues: [],
    },
    {
      label: "Phone",
      name: "SuppliedPhone",
      type: "string",
      picklistValues: [],
    },
    {
      label: "Company",
      name: "SuppliedCompany",
      type: "string",
      picklistValues: [],
    },
    {
      label: "Case Type",
      name: "Type",
      type: "picklist",
      picklistValues: [
        { label: "Mechanical", value: "Mechanical" },
        { label: "Electrical", value: "Electrical" },
        { label: "Electronic", value: "Electronic" },
        { label: "Structural", value: "Structural" },
        { label: "Other", value: "Other" },
      ],
    },
    {
      label: "Status",
      name: "Status",
      type: "picklist",
      picklistValues: [
        { label: "New", value: "New" },
        { label: "Working", value: "Working" },
        { label: "Escalated", value: "Escalated" },
        { label: "Closed", value: "Closed" },
      ],
    },
    {
      label: "Case Reason",
      name: "Reason",
      type: "picklist",
      picklistValues: [
        { label: "Installation", value: "Installation" },
        { label: "Equipment Complexity", value: "Equipment Complexity" },
        { label: "Performance", value: "Performance" },
        { label: "Breakdown", value: "Breakdown" },
        { label: "Equipment Design", value: "Equipment Design" },
        { label: "Feedback", value: "Feedback" },
        { label: "Other", value: "Other" },
      ],
    },
    {
      label: "Case Origin",
      name: "Origin",
      type: "picklist",
      picklistValues: [
        { label: "Phone", value: "Phone" },
        { label: "Email", value: "Email" },
        { label: "Web", value: "Web" },
      ],
    },
    { label: "Subject", name: "Subject", type: "string", picklistValues: [] },
    {
      label: "Priority",
      name: "Priority",
      type: "picklist",
      picklistValues: [
        { label: "High", value: "High" },
        { label: "Medium", value: "Medium" },
        { label: "Low", value: "Low" },
      ],
    },
    {
      label: "Description",
      name: "Description",
      type: "textarea",
      picklistValues: [],
    },
    { label: "Closed", name: "IsClosed", type: "boolean", picklistValues: [] },
    {
      label: "Closed Date",
      name: "ClosedDate",
      type: "datetime",
      picklistValues: [],
    },
    {
      label: "Escalated",
      name: "IsEscalated",
      type: "boolean",
      picklistValues: [],
    },
    {
      label: "Owner ID",
      name: "OwnerId",
      type: "reference",
      picklistValues: [],
    },
    {
      label: "Created Date",
      name: "CreatedDate",
      type: "datetime",
      picklistValues: [],
    },
    {
      label: "Created By ID",
      name: "CreatedById",
      type: "reference",
      picklistValues: [],
    },
    {
      label: "Last Modified Date",
      name: "LastModifiedDate",
      type: "datetime",
      picklistValues: [],
    },
    {
      label: "Last Modified By ID",
      name: "LastModifiedById",
      type: "reference",
      picklistValues: [],
    },
    {
      label: "System Modstamp",
      name: "SystemModstamp",
      type: "datetime",
      picklistValues: [],
    },
    {
      label: "Contact Phone",
      name: "ContactPhone",
      type: "phone",
      picklistValues: [],
    },
    {
      label: "Contact Mobile",
      name: "ContactMobile",
      type: "phone",
      picklistValues: [],
    },
    {
      label: "Contact Email",
      name: "ContactEmail",
      type: "email",
      picklistValues: [],
    },
    {
      label: "Contact Fax",
      name: "ContactFax",
      type: "phone",
      picklistValues: [],
    },
    {
      label: "Internal Comments",
      name: "Comments",
      type: "textarea",
      picklistValues: [],
    },
    {
      label: "Last Viewed Date",
      name: "LastViewedDate",
      type: "datetime",
      picklistValues: [],
    },
    {
      label: "Last Referenced Date",
      name: "LastReferencedDate",
      type: "datetime",
      picklistValues: [],
    },
    {
      label: "Engineering Req Number",
      name: "EngineeringReqNumber__c",
      type: "string",
      picklistValues: [],
    },
    {
      label: "Product",
      name: "Product__c",
      type: "picklist",
      picklistValues: [
        { label: "GC1040", value: "GC1040" },
        { label: "GC1060", value: "GC1060" },
        { label: "GC3020", value: "GC3020" },
        { label: "GC3040", value: "GC3040" },
        { label: "GC3060", value: "GC3060" },
        { label: "GC5020", value: "GC5020" },
        { label: "GC5040", value: "GC5040" },
        { label: "GC5060", value: "GC5060" },
        { label: "GC1020", value: "GC1020" },
      ],
    },
    {
      label: "Potential Liability",
      name: "PotentialLiability__c",
      type: "picklist",
      picklistValues: [
        { label: "No", value: "No" },
        { label: "Yes", value: "Yes" },
      ],
    },
    { label: "CSAT", name: "CSAT__c", type: "double", picklistValues: [] },
    {
      label: "Case_ExternalId",
      name: "Case_ExternalId__c",
      type: "string",
      picklistValues: [],
    },
    {
      label: "First Contact Resolution",
      name: "FCR__c",
      type: "boolean",
      picklistValues: [],
    },
    {
      label: "Product Family",
      name: "Product_Family_KB__c",
      type: "picklist",
      picklistValues: [
        { label: "Digital Media", value: "Digital Media" },
        { label: "Accessories", value: "Accessories" },
        { label: "Laptops", value: "Laptops" },
        { label: "Tablets", value: "Tablets" },
        { label: "Phones", value: "Phones" },
      ],
    },
    {
      label: "SLA Violation",
      name: "SLAViolation__c",
      type: "picklist",
      picklistValues: [
        { label: "No", value: "No" },
        { label: "Yes", value: "Yes" },
      ],
    },
    {
      label: "SLA Type",
      name: "SLA_Type__c",
      type: "picklist",
      picklistValues: [
        { label: "Basic", value: "Basic" },
        { label: "Premium", value: "Premium" },
      ],
    },
  ],
  tracked_fields: [
    "OwnerId",
    "Reason",
    "Priority",
    "Status",
    "IsStopped",
    "Type",
    "Description",
  ],
};
const OPPORTUNITY = {
  fields: [
    { label: "Opportunity ID", name: "Id", type: "id", picklistValues: [] },
    {
      label: "Deleted",
      name: "IsDeleted",
      type: "boolean",
      picklistValues: [],
    },
    {
      label: "Account ID",
      name: "AccountId",
      type: "reference",
      picklistValues: [],
    },
    {
      label: "Record Type ID",
      name: "RecordTypeId",
      type: "reference",
      picklistValues: [],
    },
    {
      label: "Private",
      name: "IsPrivate",
      type: "boolean",
      picklistValues: [],
    },
    { label: "Name", name: "Name", type: "string", picklistValues: [] },
    {
      label: "Description",
      name: "Description",
      type: "textarea",
      picklistValues: [],
    },
    {
      label: "Stage",
      name: "StageName",
      type: "picklist",
      picklistValues: [
        { label: "Prospecting", value: "Prospecting" },
        { label: "Qualification", value: "Qualification" },
        { label: "Needs Analysis", value: "Needs Analysis" },
        { label: "Value Proposition", value: "Value Proposition" },
        { label: "Id. Decision Makers", value: "Id. Decision Makers" },
        { label: "Perception Analysis", value: "Perception Analysis" },
        { label: "Proposal/Price Quote", value: "Proposal/Price Quote" },
        { label: "Negotiation/Review", value: "Negotiation/Review" },
        { label: "Closed Won", value: "Closed Won" },
        { label: "Closed Lost", value: "Closed Lost" },
      ],
    },
    { label: "Amount", name: "Amount", type: "currency", picklistValues: [] },
    {
      label: "Probability (%)",
      name: "Probability",
      type: "percent",
      picklistValues: [],
    },
    {
      label: "Expected Amount",
      name: "ExpectedRevenue",
      type: "currency",
      picklistValues: [],
    },
    {
      label: "Quantity",
      name: "TotalOpportunityQuantity",
      type: "double",
      picklistValues: [],
    },
    {
      label: "Close Date",
      name: "CloseDate",
      type: "date",
      picklistValues: [],
    },
    {
      label: "Opportunity Type",
      name: "Type",
      type: "picklist",
      picklistValues: [
        {
          label: "Existing Customer - Upgrade",
          value: "Existing Customer - Upgrade",
        },
        {
          label: "Existing Customer - Replacement",
          value: "Existing Customer - Replacement",
        },
        {
          label: "Existing Customer - Downgrade",
          value: "Existing Customer - Downgrade",
        },
        { label: "New Customer", value: "New Customer" },
      ],
    },
    {
      label: "Next Step",
      name: "NextStep",
      type: "string",
      picklistValues: [],
    },
    {
      label: "Lead Source",
      name: "LeadSource",
      type: "picklist",
      picklistValues: [
        { label: "Web", value: "Web" },
        { label: "Phone Inquiry", value: "Phone Inquiry" },
        { label: "Partner Referral", value: "Partner Referral" },
        { label: "Purchased List", value: "Purchased List" },
        { label: "Other", value: "Other" },
      ],
    },
    { label: "Closed", name: "IsClosed", type: "boolean", picklistValues: [] },
    { label: "Won", name: "IsWon", type: "boolean", picklistValues: [] },
    {
      label: "Forecast Category",
      name: "ForecastCategory",
      type: "picklist",
      picklistValues: [
        { label: "Omitted", value: "Omitted" },
        { label: "Pipeline", value: "Pipeline" },
        { label: "Best Case", value: "BestCase" },
        { label: "Most Likely", value: "MostLikely" },
        { label: "Commit", value: "Forecast" },
        { label: "Closed", value: "Closed" },
      ],
    },
    {
      label: "Forecast Category",
      name: "ForecastCategoryName",
      type: "picklist",
      picklistValues: [
        { label: "Omitted", value: "Omitted" },
        { label: "Pipeline", value: "Pipeline" },
        { label: "Best Case", value: "Best Case" },
        { label: "Commit", value: "Commit" },
        { label: "Closed", value: "Closed" },
      ],
    },
    {
      label: "Campaign ID",
      name: "CampaignId",
      type: "reference",
      picklistValues: [],
    },
    {
      label: "Has Line Item",
      name: "HasOpportunityLineItem",
      type: "boolean",
      picklistValues: [],
    },
    {
      label: "Price Book ID",
      name: "Pricebook2Id",
      type: "reference",
      picklistValues: [],
    },
    {
      label: "Owner ID",
      name: "OwnerId",
      type: "reference",
      picklistValues: [],
    },
    {
      label: "Created Date",
      name: "CreatedDate",
      type: "datetime",
      picklistValues: [],
    },
    {
      label: "Created By ID",
      name: "CreatedById",
      type: "reference",
      picklistValues: [],
    },
    {
      label: "Last Modified Date",
      name: "LastModifiedDate",
      type: "datetime",
      picklistValues: [],
    },
    {
      label: "Last Modified By ID",
      name: "LastModifiedById",
      type: "reference",
      picklistValues: [],
    },
    {
      label: "System Modstamp",
      name: "SystemModstamp",
      type: "datetime",
      picklistValues: [],
    },
    {
      label: "Last Activity",
      name: "LastActivityDate",
      type: "date",
      picklistValues: [],
    },
    { label: "Push Count", name: "PushCount", type: "int", picklistValues: [] },
    {
      label: "Last Stage Change Date",
      name: "LastStageChangeDate",
      type: "datetime",
      picklistValues: [],
    },
    {
      label: "Fiscal Quarter",
      name: "FiscalQuarter",
      type: "int",
      picklistValues: [],
    },
    {
      label: "Fiscal Year",
      name: "FiscalYear",
      type: "int",
      picklistValues: [],
    },
    {
      label: "Fiscal Period",
      name: "Fiscal",
      type: "string",
      picklistValues: [],
    },
    {
      label: "Contact ID",
      name: "ContactId",
      type: "reference",
      picklistValues: [],
    },
    {
      label: "Last Viewed Date",
      name: "LastViewedDate",
      type: "datetime",
      picklistValues: [],
    },
    {
      label: "Last Referenced Date",
      name: "LastReferencedDate",
      type: "datetime",
      picklistValues: [],
    },
    {
      label: "Has Open Activity",
      name: "HasOpenActivity",
      type: "boolean",
      picklistValues: [],
    },
    {
      label: "Has Overdue Task",
      name: "HasOverdueTask",
      type: "boolean",
      picklistValues: [],
    },
    {
      label: "Opportunity History ID",
      name: "LastAmountChangedHistoryId",
      type: "reference",
      picklistValues: [],
    },
    {
      label: "Opportunity History ID",
      name: "LastCloseDateChangedHistoryId",
      type: "reference",
      picklistValues: [],
    },
    {
      label: "Delivery/Installation Status",
      name: "DeliveryInstallationStatus__c",
      type: "picklist",
      picklistValues: [
        { label: "In progress", value: "In progress" },
        { label: "Yet to begin", value: "Yet to begin" },
        { label: "Completed", value: "Completed" },
      ],
    },
    {
      label: "Tracking Number",
      name: "TrackingNumber__c",
      type: "string",
      picklistValues: [],
    },
    {
      label: "Order Number",
      name: "OrderNumber__c",
      type: "string",
      picklistValues: [],
    },
    {
      label: "Current Generator(s)",
      name: "CurrentGenerators__c",
      type: "string",
      picklistValues: [],
    },
    {
      label: "Main Competitor(s)",
      name: "MainCompetitors__c",
      type: "string",
      picklistValues: [],
    },
    {
      label: "Opportunity Source",
      name: "Opportunity_Source__c",
      type: "string",
      picklistValues: [],
    },
  ],
  tracked_fields: [
    "Amount",
    "ForecastCategoryName",
    "NextStep",
    "OwnerId",
    "Opportunity_Source__c",
    "Probability",
    "TotalOpportunityQuantity",
    "StageName",
    "Type",
    "Description"
  ]
};
export { CASE, OPPORTUNITY };
